import json
import os
from core.physics_engine import SquareToothPhysics
from core.telemetry_bridge import TelemetryBridge
import math
import sys

# Add core to path so we can import the engine we built earlier
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'core')))
from physics_engine import HexNativeSquareToothEngine

class DynamicGeneratorScaler:
    """
    Takes user-defined dimensions and generates a strict parametric configuration
    for the OpenSCAD manufacturing pipeline.
    """
    def __init__(self):
        self.output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'hardware'))
        
    def generate_scad_configuration(self, diameter_mm, target_rpm, power_w, fluid_type):
        print(f"\n[SCALER] Calculating dynamic parameters for a {diameter_mm}mm {fluid_type.upper()} generator...")
        
        # Initialize the physics engine
        engine = HexNativeSquareToothEngine(fluid_type=fluid_type, power_target_w=power_w, target_rpm=target_rpm)
        
        # 1. Calculate Torques & Shafts
        angular_vel = (target_rpm * 2 * math.pi) / 60.0
        torque = power_w / angular_vel
        shaft_dia_mm = engine.size_titanium_shaft(torque)
        
        # 2. Calculate Hex Sync Teeth
        z_teeth, hex_hz = engine.calculate_hex_tooth_matrix()
        
        # 3. Calculate Acoustic Housing Length
        # Assume titanium wall is 3% of the total diameter
        wall_thick_mm = diameter_mm * 0.03
        housing_length_mm = engine.calculate_acoustic_silencer_length(z_teeth, wall_thick_mm, diameter_mm)
        
        # 4. Calculate Hydrodynamic Clearances
        max_gap_mm, chevron_mm = engine.calculate_active_clearance_gap(diameter_mm)
        
        # Write to OpenSCAD Parameter File
        scad_path = os.path.join(self.output_dir, "dynamic_parameters.scad")
        with open(scad_path, "w") as f:
            f.write("/* AUTO-GENERATED BY GENERATOR_SCALER.PY */\n")
            f.write("/* DO NOT EDIT MANUALLY. */\n\n")
            f.write(f"rotor_diameter = {diameter_mm};\n")
            f.write(f"shaft_diameter = {shaft_dia_mm:.3f};\n")
            f.write(f"housing_length = {housing_length_mm:.3f};\n")
            f.write(f"housing_thickness = {wall_thick_mm:.3f};\n")
            f.write(f"z_teeth = {z_teeth};\n")
            f.write(f"max_tip_gap = {max_gap_mm:.4f};\n")
            f.write(f"chevron_depth = {chevron_mm:.4f};\n")
            
        print(f"[SCALER] SUCCESS. Exported parametric constraints to {scad_path}.")
        return scad_path
    
    # Simple dynamic user inputs
    environment = input("Enter environment type (hydro / wind / combustion_fuel): ").strip()
    target_power = float(input("Enter Target Power Output (Watts): "))
    target_rpm = float(input("Enter Target Operating Speed (RPM): "))
    
    # Load configuration profiles
    config_path = os.path.join(os.path.dirname(__file__), '../config/environment_profiles.json')
    with open(config_path, 'r') as f:
        profiles = json.load(f)
        
    if environment not in profiles:
        print("Invalid environment selection.")
        return

    # Process Physics & Materials
    engine = SquareToothPhysics(profiles[environment])
    min_shaft_dia = engine.calculate_shaft_diameter(target_power, target_rpm, bending_moment=(target_power*0.01))
    
    # Process Telemetry Matrix Alignment
    teeth = TelemetryBridge.calculate_hex_tooth_matrix(target_rpm)
    actual_freq = TelemetryBridge.generate_hex_sync_frequency(target_rpm, teeth)
    
    # Format and Output Results Dynamically
    print("\n--- DESIGN SPECIFICATIONS GENERATED ---")
    print(f"Fluid Density Mapped: {profiles[environment]['fluid_density_rho']} kg/m3")
    print(f"Minimum Titanium Shaft Core Diameter: {min_shaft_dia * 1000:.2f} mm")
    print(f"Optimized Synchronous Square-Tooth Pattern: {teeth} Teeth (Hex-Aligned Cluster)")
    print(f"Resulting Telemetry Signal Wave Frequency: {actual_freq:.1f} Hz")

if __name__ == "__main__":
    scaler = DynamicGeneratorScaler()
    # In a real environment, you'd use argparse or input() here.
    # We are simulating a user asking for a 1.2-meter wind turbine pushing 200kW
    scaler.generate_scad_configuration(diameter_mm=1200.0, target_rpm=120, power_w=200000, fluid_type="wind")
def run_scaling_engine():
    print("=== Square-Tooth Generator Parametric Sizing Engine ===")
