/**
 * =========================================================================
 * SQUARE-TOOTH GENERATOR INFRASTRUCTURE Matrix
 * MCP4725 Multi-Channel 16-State Voltage Injection Controller
 * Targets 16 distinct voltage steps within a precise 0.0V to 1.0V window.
 * =========================================================================
 */
// In src/dac_mcp4725.c:
#include "dac_mcp4725.h"

uint16_t calculate_12bit_dac_value(const MCP4725_Device *device, char hex_token) {
    // Implementation code updated to use device->reference_voltage_v and device->target_voltage_max_v
}

DAC_Status write_mcp4725_step(const MCP4725_Device *device, char hex_token) {
    // Implementation code updated to use device->i2c_bus_fd and device->device_address
}

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <linux/i2c-dev.h>

/* Physical Silicon Constraints */
#define DAC_RESOLUTION_STEPS 4096   // 12-bit DAC depth (0 to 4095)
#define V_REF_TOTAL          5.0f   // Hardware System Supply Voltage Rails (VCC)
#define TARGET_V_MAX         1.0f   // Maximum operational boundary for your logic lane

/* Multi-Channel I2C Bus Address Assignments (Configured via A0 pin layouts) */
#define CHANNEL_0_ADDRESS    0x62   // Primary 16-state lane DAC
#define CHANNEL_1_ADDRESS    0x63   // Secondary redundant telemetry lane DAC

/* MCP4725 I2C Write Command Modes */
#define CMD_FAST_WRITE       0x00   // Updates the DAC register immediately (Fastest execution loop)
#define CMD_WRITE_EEPROM     0x60   // Writes to both DAC register and internal EEPROM cell

/**
 * Maps a single Hex token (0-F) directly to its mathematical 12-bit DAC register integer.
 * Enforces strict 66.66mV intervals up to your 1.0V max ceiling.
 */
uint16_t calculate_12bit_dac_value(char hex_token) {
    uint8_t numeric_state = 0;
    
    // Parse hex character to its baseline raw integer step value
    if (hex_token >= '0' && hex_token <= '9') {
        numeric_state = hex_token - '0';
    } else if (hex_token >= 'A' && hex_token <= 'F') {
        numeric_state = hex_token - 'A' + 10;
    } else if (hex_token >= 'a' && hex_token <= 'f') {
        numeric_state = hex_token - 'a' + 10;
    } else {
        // Fallback safety baseline if signal is corrupted
        return 0;
    }
    
    // Compute targeted analog voltage level (15 uniform steps across 16 states)
    float target_voltage = ((float)numeric_state / 15.0f) * TARGET_V_MAX;
    
    // Convert target voltage to exact 12-bit integer register step value
    uint16_t dac_register_value = (uint16_t)((target_voltage * (float)DAC_RESOLUTION_STEPS) / V_REF_TOTAL);
    
    // Prevent buffer overflows past maximum limits
    if (dac_register_value > 4095) {
        dac_register_value = 4095;
    }
    
    return dac_register_value;
}

/**
 * Transmits a 12-bit configuration byte sequence down the selected I2C hardware bus lane.
 */
int write_mcp4725_step(int i2c_file_desc, uint8_t i2c_device_address, char hex_token) {
    uint16_t dac_raw_value = calculate_12bit_dac_value(hex_token);
    uint8_t transmit_buffer[3];
    
    // Enforce target device address routing on the bus
    if (ioctl(i2c_file_desc, I2C_SLAVE, i2c_device_address) < 0) {
        perror("[ERROR]: Failed to route signal focus to targeted physical DAC channel");
        return -1;
    }
    
    // Pack the 12-bit payload using MCP4725 Fast Write Mode formatting requirements
    // Buffer Byte 0: [Upper Control Bits (4 bits)] | [Upper 4 bits of the 12-bit data]
    transmit_buffer[0] = CMD_FAST_WRITE | ((dac_raw_value >> 8) & 0x0F);
    // Buffer Byte 1: [Lower 8 bits of the 12-bit data]
    transmit_buffer[1] = dac_raw_value & 0xFF;
    
    // Execute synchronous physical line write sequence
    if (write(i2c_file_desc, transmit_buffer, 2) != 2) {
        perror("[ERROR]: Core trace transmission failure or I2C bus collision");
        return -1;
    }
    
    return 0;
}

int main() {
    printf("=== MCP4725 Multi-Channel Firmware Driver Initialization ===\n");
    
    // Open access path to primary physical I2C bus peripheral driver layer
    int i2c_bus_fd = open("/dev/i2c-1", O_RDWR);
    if (i2c_bus_fd < 0) {
        perror("[CRITICAL]: Failed to open internal hardware system I2C master bus channel");
        return 1;
    }
    
    // Simulate transmitting a telemetry sequence generated by your 108-bit register
    char telemetry_stream[] = "F84A0C3D";
    int stream_length = 8;
    
    printf("[FIRMWARE RUNTIME]: Processing stream queue transmission sequence...\n");
    
    for (int i = 0; i < stream_length; i++) {
        char current_token = telemetry_stream[i];
        
        // Inject data onto Channel 0 (Main Telemetry Bus)
        int status_ch0 = write_mcp4725_step(i2c_bus_fd, CHANNEL_0_ADDRESS, current_token);
        
        // Mirror data to Channel 1 for dual-redundant structural safety verification
        int status_ch1 = write_mcp4725_step(i2c_bus_fd, CHANNEL_1_ADDRESS, current_token);
        
        if (status_ch0 == 0 && status_ch1 == 0) {
            printf("  Token [0x%c] -> Scaled Registers Written. Output Synchronized.\n", current_token);
        }
        
        // Small delay to allow voltage stabilization across your guard traces (e.g., 50ms)
        usleep(50000); 
    }
    
    // Safely tear down file descriptors and close bus resources
    close(i2c_bus_fd);
    printf("[SUCCESS]: Stream successfully pushed down hardware traces. Bus state returned to IDLE.\n");
    return 0;
}
